name: KatieCresswell
favicon: null
layout_spectrum: 0.7516297299880534
typography_spectrum: 0.7098693528678268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8766658424865454
  lightness: 0.4329281465616077
  saturation: 0.83140306500718
  rhythmicContrast: 0.08766741887666285
purpose: []
